# Generated by Django 4.2.4 on 2024-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_product_stock_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Shipped', 'Shipped')], default='Pending', max_length=20),
        ),
    ]
