# Generated by Django 4.2.4 on 2024-10-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Shipped', 'Shipped'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
